name: Send Email

on:
  workflow_dispatch:
  push:
    branches: [main]
  # schedule:
  #   - cron: '0 22 * * 0'  # Runs every Monday 6:00 AM (Asia/Manila, UTC+8)

jobs:
  send_email:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    env:
      COMMIT_MSG: ${{ github.event.head_commit.message || '' }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch and merge runner branch
        run: |
          git fetch origin runner
          git merge origin/runner --no-edit || echo "Nothing to merge"

      - name: Set up Python and install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Email Script if not an Update commit
        if: ${{ !startsWith(env.COMMIT_MSG, 'Update') }}
        run: python SSR_HTML_EMAIL/html_emailer.py

      - name: Auto commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update: auto changes by email script"
