name: Send Email

on:
  workflow_dispatch:
  push:
    branches: [main]
  # schedule:
  #   - cron: '0 22 * * 0'  # Runs every Monday 6:00 AM (Asia/Manila, UTC+8)
    
jobs:
  send_email:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    env:
      COMMIT_MSG: ${{ github.event.head_commit.message }}

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Merge changes from runner into main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin runner
          git merge origin/runner --no-edit || echo "Already up to date"
          
      - name: Run script
        if: ${{ !startsWith(env.COMMIT_MSG,'Update') }}
        shell: bash
        run: |
          chmod +x SSR.sh
          ./SSR.sh
      - uses: stefanzweifel/git-auto-commit-action@v6.0.1
