name: Send Email

on:
  workflow_dispatch:
  schedule:
    - cron: '59 15 * * 0'
    
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        shell: bash
        run: |
          chmod +x SSR.sh
          ./SSR.sh
      - uses: stefanzweifel/git-auto-commit-action@v6.0.1
