name: Test Send Email

on:
  workflow_dispatch:
  push:
    branches: [runner]

jobs:
  test_send_email:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    env:
      COMMIT_MSG: ${{ github.event.head_commit.message }}
      COMMIT_AUTHOR: ${{ github.event.head_commit.author.username }}

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0

      - name: Merge changes from runner into main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin runner
          git merge origin/runner --no-edit || echo "Already up to date"

      - name: Run script with commit message
        if: ${{ !startsWith(env.COMMIT_MSG,'Update') && !startsWith(env.COMMIT_AUTHOR, 'github-actions') }}
        run: |
          chmod +x SSR.sh
          ./SSR.sh "${{ env.COMMIT_MSG }}"

      - name: Auto-commit changes (if any)
        if: ${{ !startsWith(env.COMMIT_AUTHOR, 'github-actions') }}
        uses: stefanzweifel/git-auto-commit-action@v6.0.1